name: eraser
description: A flutter plugin that allows remote push notifications to be dismissed and the iOS badge count to be reset.
version: 2.0.2
homepage: https://github.com/Wes1324/eraser

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.wescj.eraser
        pluginClass: EraserPlugin
      ios:
        pluginClass: EraserPlugin